"""add_knowledge_chunks_table

Revision ID: 013065484c78
Revises: eaad580f9809
Create Date: 2026-05-17 00:15:15.872122+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

try:
    from pgvector.sqlalchemy import Vector as PgVector
except ImportError:
    PgVector = None

# revision identifiers, used by Alembic
revision: str = '013065484c78'
down_revision: Union[str, None] = 'eaad580f9809'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    has_vector = conn.execute(
        sa.text("SELECT 1 FROM pg_available_extensions WHERE name = 'vector'")
    ).fetchone() is not None
    if has_vector:
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")
        embedding_col = "embedding vector(1536)"
    else:
        embedding_col = "embedding TEXT"
    op.execute(f"""
        CREATE TABLE IF NOT EXISTS knowledge_chunks (
            id SERIAL NOT NULL,
            knowledge_id VARCHAR(100) NOT NULL,
            original_filename VARCHAR(500) NOT NULL,
            chunk_index INTEGER NOT NULL,
            chunk_text TEXT NOT NULL,
            token_count INTEGER,
            {embedding_col},
            created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
            PRIMARY KEY (id)
        )
    """)
    op.create_index('idx_knowledge_chunks_knowledge_id', 'knowledge_chunks', ['knowledge_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_knowledge_id'), 'knowledge_chunks', ['knowledge_id'], unique=False)
    op.drop_index(op.f('idx_brands_name'), table_name='brands')
    op.drop_index(op.f('idx_categories_name'), table_name='categories')
    op.alter_column('products', 'item_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'is_best_selling',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('idx_products_brand_id'), table_name='products')
    op.drop_index(op.f('idx_products_category_id'), table_name='products')
    op.drop_index(op.f('idx_products_concerns'), table_name='products', postgresql_using='gin')
    op.drop_index(op.f('idx_products_item_name_trgm'), table_name='products', postgresql_ops={'item_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_products_sap_product_id'), table_name='products')
    op.drop_index(op.f('idx_products_subcategory_id'), table_name='products')
    op.drop_index(op.f('idx_products_tags'), table_name='products', postgresql_using='gin')
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.create_index(op.f('ix_products_brand_id'), 'products', ['brand_id'], unique=False)
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_sap_product_id'), 'products', ['sap_product_id'], unique=False)
    op.create_index(op.f('ix_products_subcategory_id'), 'products', ['subcategory_id'], unique=False)
    op.drop_index(op.f('idx_productsearchindex_brand_id'), table_name='productsearchindex')
    op.drop_index(op.f('idx_productsearchindex_category_id'), table_name='productsearchindex')
    op.drop_index(op.f('idx_productsearchindex_subcategory_id'), table_name='productsearchindex')
    op.drop_index(op.f('idx_search_text_gin'), table_name='productsearchindex', postgresql_using='gin')
    op.drop_column('productsearchindex', 'category_id')
    op.drop_column('productsearchindex', 'brand_id')
    op.drop_column('productsearchindex', 'subcategory_id')
    op.drop_index(op.f('idx_subcategories_category_id'), table_name='subcategories')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_subcategories_category_id'), 'subcategories', ['category_id'], unique=False)
    op.add_column('productsearchindex', sa.Column('subcategory_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('productsearchindex', sa.Column('brand_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('productsearchindex', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_search_text_gin'), 'productsearchindex', [sa.literal_column("to_tsvector('english'::regconfig, search_text)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_productsearchindex_subcategory_id'), 'productsearchindex', ['subcategory_id'], unique=False)
    op.create_index(op.f('idx_productsearchindex_category_id'), 'productsearchindex', ['category_id'], unique=False)
    op.create_index(op.f('idx_productsearchindex_brand_id'), 'productsearchindex', ['brand_id'], unique=False)
    op.drop_index(op.f('ix_products_subcategory_id'), table_name='products')
    op.drop_index(op.f('ix_products_sap_product_id'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_index(op.f('ix_products_brand_id'), table_name='products')
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=False)
    op.create_index(op.f('idx_products_tags'), 'products', ['tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_products_subcategory_id'), 'products', ['subcategory_id'], unique=False)
    op.create_index(op.f('idx_products_sap_product_id'), 'products', ['sap_product_id'], unique=False)
    op.create_index(op.f('idx_products_item_name_trgm'), 'products', ['item_name'], unique=False, postgresql_ops={'item_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_products_concerns'), 'products', ['concerns'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('idx_products_brand_id'), 'products', ['brand_id'], unique=False)
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('products', 'is_best_selling',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=False)
    op.alter_column('products', 'item_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('idx_categories_name'), 'categories', ['name'], unique=False)
    op.create_index(op.f('idx_brands_name'), 'brands', ['name'], unique=False)
    op.drop_index(op.f('ix_knowledge_chunks_knowledge_id'), table_name='knowledge_chunks')
    op.drop_index('idx_knowledge_chunks_knowledge_id', table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    # ### end Alembic commands ###
